### ISSUE TITLE
Большие методы

### ISSUE THREAD

**Issue by Frolikow** [pasha-zolotukhin/range-slider#5]
В модели у тебя сейчас есть метод "_checkConfigTypes" аж на 70+ строк. Ему точно там лучше находиться? Если его вынести в отдельную функцию, а в модели подключать и вызывать при необходимости? Тут ты еще и конструктор модели уменьшишь, убрав из него большую пачку констант "this._error"

**Comment by pasha-zolotukhin** [comment]
Не понял, что имелось в виду про "вынести в отдельную функцию"? Объем метода от этого же уменьшится)

**Comment by Frolikow** [comment]
Я про вынесение метода вообще в отдельный файл) в том и дело что он вызывается один раз, но при этом занимает в сумме 100+ строк кода в модели)

**Comment by pasha-zolotukhin** [comment]
Просто этот метод - это часть метода validate и отрывать его будет не оч.

**Comment by chmnkh** [comment]
> Просто этот метод - это часть метода validate и отрывать его будет не оч.

Справедливо.

> Ну и выносить просто в функцию - это привет процедурный стиль) А у нас ООП.

Тоже в какой-то степени справедливо. А что тебе мешает, например, ответственность таким образом разделить, чтобы за валидацию конфига какой-то отдельный класс отвечал, например? 

Здесь на самом деле речь о том, чтобы таким образом разбить ответственность, чтобы с кодом было как можно проще работать. Ты можешь, конечно, на модель оставить не только расчет, но и валидацию тоже, но у тебя тогда модель по фукнциональности будет жирнее, а это значит, что с ней будет тупо сложнее работать. 

Что-то куда-то вынести - вообще один из самых тупых (и притом действенных) способов уменьшить сложность чего-то. Работать с двумя маленькими файлами проще, чем с одним большим.  Разумеется, ты не можешь просто так взять и растащить функциональность класса по разным файлам. Но когда ты можешь адекватно разделить ответственность так, чтобы часть класса куда-то вынести - почему нет? Здесь можно это сделать: ты можешь на совесть модели состояние слайдера, и всю валидацию вынести в какой-то отдельный модуль. Здесь просто Егор немного не учел, что функциональность валидации относительно жирная, и тянет за собой много всего.

Просто дело в том, что валидация сейчас в коде модели много шума создает, который в целом для понимания логики слайдера не нужен. Тем более, что довольно большая часть валидации - это компенсация того, что статическая типизация отсутствует, и нам может прилететь любая дичь в аргументы. 

Как-то так. Если у тебя есть аргументы против, или тебе кажется, что я где-то сказал чушь или что-то не учел, высказывай)

**Comment by pasha-zolotukhin** [comment]
Можно попробовать вынести в отдельный класс Config.

**Comment by pasha-zolotukhin** [comment]
Я убрал из модели некоторые проверки типа таких

`if (typeof observer !== 'function') {`
`throw new Error(this._error.OBSERVER_SHOULD_BE_FUNCTION);`
`}`

Чтобы полностью избавиться от объекта error (в конфиге оставил).

**Comment by pasha-zolotukhin** [comment]
Но меня напрягает, что теперь везде нужно писать this._config.getConfig().

**Comment by chmnkh** [comment]
Ну да, на самом деле не очень элегантно вышло.
Я скорее имел в виду сделать не класс для управления конфигом вообще, а класс, который бы тупо валидацией/нормализацией занимался, типа там `ConfigValidator` или `ConfigNormalizer`. Условно, если модели прилетел новый конфиг, она бы использовала этот класс для валидации/нормализации. Тогда у тебя бы не было этих проблем с гетконфигом, потому что сам конфиг был бы частью модели, но она просто бы использовала какую-то вспомогательную штуку для того, чтобы этот конфиг был в адекватном состоянии. Т.е. этот класс был бы чисто вспомогательным, а никакого состояния не хранил бы.

**Comment by pasha-zolotukhin** [comment]
@Frolikow @chmnkh 

Создал класс ConfigNormalizer и вынес туда приватные методы. validate оставил в модели, т.к. он юзает конфиг + можно не менять доки.

Ну и такие проверки в модели убрал:
`if (typeof observer !== 'function') {`
`throw new Error(this._error.OBSERVER_SHOULD_BE_FUNCTION);`
`}`
