### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by chmnkh** [pasha-zolotukhin/range-slider#8]
Можешь расписать, почему у тебя архитектура реализована сейчас так, как реализована? Я вообще про разделение ответственности между моделью/вьюхой/контроллером. Почему вьюха на модель подписана, например? Почему события именно в контроллере слушаются? И всякое такое. 

Ну т.е. там же много вариантов, как с этим работать (я имею в виду есть много вариантов: MVC, MVP, MVVM и т.д.), почему ты именно такой способ выбрал?

**Comment by pasha-zolotukhin** [comment]
> Ну т.е. там же много вариантов, как с этим работать (я имею в виду есть много вариантов: MVC, MVP, MVVM и т.д.), почему ты именно такой способ выбрал?

В задании было сказано про MVC, поэтому я не рассматривал его ответвления.

> Можешь расписать, почему у тебя архитектура реализована сейчас так, как реализована? Я вообще про разделение ответственности между моделью/вьюхой/контроллером. Почему вьюха на модель подписана, например? Почему события именно в контроллере слушаются? И всякое такое.

На самом деле это сложный для меня вопрос. Как я понял, MVC можно реализовать по-разному. В данном случае это просто первая проба, так сказать. Лично я реализовывал, полагаясь на статьи с хабра: [один](https://habr.com/ru/post/119369/), [два](https://habr.com/ru/post/321050/). Вот в первой статье автор как раз реализует так, что вью подписывается на модель, а контроллер содержит события.

**Comment by chmnkh** [comment]
Окей, справедливо.

Тогда в рамках варианта MVC, который ты реализовал, и будем смотреть.
